### ISSUE TITLE
plugin install on git

### ISSUE THREAD

**Issue by serbasii** [alerta/alerta#1040]
im working as linux container for windows and try to install the plugin in container. im getting permission error.

> pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/amqp

>  Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/vine'
> Consider using the `--user` option or check the permissions.

and trying with --user, no way.

**Comment by serbasii** [comment]
same on mac

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
