### ISSUE TITLE
Grafana Webhook Integration:  Looks for `tags` in the wrong part of the json payload

### ISSUE THREAD

**Issue by travis-bear** [alerta/alerta#1091]
**Issue Summary**
Grafana webhook doesn't convert the tags sent by Grafana into custom attributes.  This appears to be because in Grafana.py, it's looking in the wrong part of the incoming json document for the tags.

Here's the incoming alert payload from Grafana version 6.3.6, which is the newest version:

    { 
       "evalMatches":[ 
          { 
             "value":323.4,
             "metric":"samples",
             "tags":{ 
             }
          }
       ],
       "message":"Here's my message",
       "ruleId":12,
       "ruleName":"Samples Appended alert",
       "ruleUrl":"http://grafana.monitor.aort.<...>.com/d/itBdm3dZz/prometheus-health?fullscreen\\u0026edit\\u0026tab=alert\\u0026panelId=3\\u0026orgId=1",
       "state":"alerting",
       "tags":{ 
          "arbitrary_key":"arbitrary_val",
          "dashboard":"my dashboard",
          "slack":"my_slack",
          "tsg":"my tsg"
       },
       "title":"[Alerting] Samples Appended alert"
    }

Here's the Grafana alert config:

<img width="683" alt="Screen Shot 2019-10-02 at 4 04 09 PM" src="https://user-images.githubusercontent.com/505972/66089546-b63caa80-e534-11e9-9e58-f3959a20a76c.png">

In Alerta's grafana code (https://github.com/alerta/alerta/blob/master/alerta/webhooks/grafana.py#L33) it appears to be building custom attributes from the tag data from some `match` stanza rather than the top-level `tags` stanza where the sent tags are actually located.

**Comment by satterly** [comment]
This must have changed at some point because the test cases are based on payloads that look like this ...
```
        {
            "evalMatches": [
                {
                    "value": 97.007606,
                    "metric": "user",
                    "tags": {
                        "__name__": "netdata_cpu_cpu_percentage_average",
                        "chart": "cpu.cpu0",
                        "dimension": "user",
                        "family": "utilization",
                        "instance": "zeta.domain",
                        "job": "monitoring",
                        "info.host_id": "i-0d0721c7f97545d43"
                    }
                }
            ],
            "message": "boom!",
            "ruleId": 7,
            "ruleName": "Zeta CPU alert",
            "ruleUrl": "https://grafana.domain.tld/dashboard/db/alarms?fullscreen&edit&tab=alert&panelId=1&orgId=1",
            "state": "alerting",
            "title": "[Alerting] CPU alert"
        }
```

**Comment by travis-bear** [comment]
Maybe the best approach is to look for the tags in both locations.

**Comment by satterly** [comment]
Looks like AlertRuleTags were added to webhook payload in Grafana 6.4. See https://github.com/grafana/grafana/pull/18233

Example ...
```
{
  "evalMatches": [
    {
      "value": 23644.5,
      "metric": "Battery Voltage (millivolts)",
      "tags": null
    }
  ],
  "message": "Battery Voltage dropped below 23.7 Volts, please investigate",
  "ruleId": 58,
  "ruleName": "Testing -> Battery Voltage alert",
  "ruleUrl": "https://grafana.logreposit.com/d/Rs6E_oHWk/playground?fullscreen&edit&tab=alert&panelId=2&orgId=1",
  "state": "alerting",
  "tags": {
    "enabled": "true",
    "relay": "7",
    "on-alerting": "relay-on",
    "on-ok": "ignore"
  },
  "title": "[Alerting] TEST -> Battery Voltage alert"
}
```

**Comment by kjetilmjos** [comment]
When you set up Alerta as a notification channel in Grafana you can set tag in the webhook url. Before version 6.4 this was the only way to add tags. Now tags are possible to set on each alert as well directly from Grafana. This is a nice feature as it gives more flexibility, and the Alerta-Grafana webhool should have support for it. But I think the old way of settings tags directly in the url should be kept. If you have a tag you want to set on all alerts you can set it in the url instead of having to set the tag manually on every individual alert that is created.

**Comment by n0guest** [comment]
### Less "Notification channels" in Grafana

But what about overriding env/group/service/etc from tags? Right now it's only possible [via request.args](/alerta/alerta/blob/master/alerta/webhooks/grafana.py#L26) which requires one to set few URL's in Grafana's "notification channels" just to specify different values. Isn't it more convenient to override those values via tags and avoid creating extra "notification channels"? I'm talking about  having only this:

```
https://alerta.domain.tld/api/webhooks/grafana?api-key=keyhere
```

Instead of having many like this:

```
https://alerta.domain.tld/api/webhooks/grafana?api-key=keyhere&environment=UrlEnv1&event_type=UrlEvent1&group=UrlGroup1&origin=UrlOrigin1&service=UrlService1&timeout=3600
https://alerta.domain.tld/api/webhooks/grafana?api-key=keyhere&environment=UrlEnv2&event_type=UrlEvent2&group=UrlGroup2&origin=UrlOrigin2&service=UrlService2&timeout=7200
...MORE...
```

It could reduce time expense to maintain such lists.

### Use subkeys of evalMatchers => tags

And even more convenient (but maybe little more complex) would be to use values from subkeys of `evalMatches => tags` from JSON payload. It would allow to use metric labels, which available as query result (at least in case of Prometheus). For example, if you have query like this:

```
sum(netdata_system_cpu_percent{chart="system.cpu",dimension="idle",env="reserve",family="cpu",group="demo2",instance="serverX",job="testing",source="someValue"}) by (instance,dimension)
```

You would see this subsection in payload:

```json
  "evalMatches": [
    {
      "metric": "serverX/idle",
      "tags": {
        "dimension": "idle",
        "instance": "serverX"
      },
      "value": 77.44831865102118
    }
  ]
```

As you can see, this data is already available and subkeys of tags could be used for filling in following `Alert` dictionary. I.e. I suggest instead of this:

```
args.get('environment', 'Production')
```

To use available subkeys of `evalMatches => tags`. And to follow "complexity" mentioned above - why not to use freshly added "tags" from JSON payload? I.e. resulting order should be something like this (lower elements in list below should have higher priority):

1. values from `args.get(ArgsFromURL, default)` as current "hardcoded" behavior from grafana.py
2. subkeys from `evalMatches => tags` (i.e. using labels from results of query execution)
3. freshly added tags from Grafana 6.4.x (if they are present in payload)

Possibly the 2nd option could be omitted in favor of just having "values from tags as an override for env/group/service/etc". 

### Use tags from Grafana's payload

It would at least allow to override some fields in alert by using custom tags in alert parameters (on Grafana's side). And also reduce a toll on maintaining long list of "notification channels" with little difference in URL params.

What do you think about it?

**Comment by kjetilmjos** [comment]
Sounds like a good idea to me. Could possibly be done in the way that hardcoding tags etc in the webhook url is supported, but if you instead use tags in the alert it will override the webhook tags?

The thing I'm worried about is that if I need to set a specific environment on an alert it will be more work tagging all individual alert than maintaining a couple of webhook url's.

**Comment by n0guest** [comment]
> The thing I'm worried about is that if I need to set a specific environment on an alert it will be more work tagging all individual alert than maintaining a couple of webhook url's.

Yep, it's "the other side of the coin". By combining both ways we're providing end users a choice how to use it in their own specific case. The only consequence of such decision - complexity of logic in code. But as the say - "there is always a trade off".

> The thing I'm worried about is that if I need to set a specific environment on an alert it will be more work tagging all individual alert than maintaining a couple of webhook url's.

As I wrote above, having both scenarios will allow you or anyone else to use the "better" for them - by handling the list of URL's (with overrided params as query args) or by specifying addition custom tags in specific alert at Grafana (to override the same params).

So, @satterly, what do you think on that matter?

**Comment by n0guest** [comment]
@satterly, could you share your point of view on offered solution? If you agree, I'd like to send a PR for your approval.

**Comment by satterly** [comment]
@n0guest I like the sound of this as a first iteration ...
> Possibly the 2nd option could be omitted in favor of just having "values from tags as an override for env/group/service/etc".

Please proceed with a PR if you still have time. Thanks.

**Comment by psyhomb** [comment]
Hey guys, anything new on this topic?

**Comment by psyhomb** [comment]
I have created a PR :arrow_up:, so @satterly when you find time could you please review it and see if there is anything else that has to be done.

Thanks
