### ISSUE TITLE
ldap auth allows empty password

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta#1103]
When using ldap auth there is no error returned for an empty password. This allows users to login without a password since the simple bind does not return "INVALID CREDENTIALS" when sending an empty password (at least in our environment)

- OS: Linux
- API version: 7.4
- Deployment: self hosted
- For self-hosted, WSGI environment: nginx/uwsgi

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
This is a mis-configuration of your LDAP server nothing to do with python-ldap or Alerta. See https://github.com/python-ldap/python-ldap/issues/174
