### ISSUE TITLE
Alerta configuration

### ISSUE THREAD

**Issue by fsaunier-ops** [alerta/alerta#1112]
**Issue Summary**
We see latencies on post APIs when the configuration is 50 messages / second

**Environment**
- OS: CentOS 7
- Deployment: Docker

**Expected behavior**
We find latencies of the order of 3-4 minutes

**Comment by satterly** [comment]
Where do you see the latency? In the API, in the database, in the response? Using curl or in a web browser? You need to provide more info. There was an issue template you could have filled in. You should also provide logs.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).
