### ISSUE TITLE
Not able to set environment

### ISSUE THREAD

**Issue by ChaitanyaManthena** [alerta/alerta#1178]
Hi Team,

I am running the alertad and couldn't able to set environment as it default getting Production for all the installations. Tried using the below properties but didn't help, request you to help on this.

environment= 'Test'
ALERTA_DEFAULT_PROFILE = 'Test'

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by ChaitanyaManthena** [comment]
Hi @satterly 
While running the alertad the environment is coming default as production and not able to override with the current environment or not able to change the environment label in Alerta UI. I request you to help in right variables setting the environment in /etc/alertad.conf

**Comment by satterly** [comment]
Where is the "environment" coming from? What commands are you running to generate alerts?
Also please share your `alertad.conf` file. Thanks.

**Comment by ChaitanyaManthena** [comment]
@satterly 
Thank you so much for your quick reply, I am able to route all the alerts to specific environment by below configurations in alertmanager. Is this the way to do or is there any best way to do so. Also I wanted to check is there any documentation to deploy alerta server by uWsgi in RHEL, i found in ubuntu but facing some challenges in RHEL.

global
  external_labels:
    environment: Test

**Comment by satterly** [comment]
This is why I ask people to fill in the issue template. If you had said right from the start you were using Prometheus Alertmanager then I would've been able to help you faster. 

Set `ALLOWED_ENVIRONMENTS` as per this web page ... https://docs.alerta.io/en/latest/configuration.html#plugin-settings

**Comment by ChaitanyaManthena** [comment]
thank you.. 👍
