### ISSUE TITLE
Ticketing System integration 

### ISSUE THREAD

**Issue by RandallGitHub** [alerta/alerta#1328]
Hello, 

I was wondering if there is any previous experience integrating Alerta with any ITSM / Ticketing System such as ServiceNow? For example, via RESTApi? We are interested in Alerta and would like to explore this possibility, if no previous experience any advise is appreciated.

**Comment by satterly** [comment]
There is no specific example I know of where someone has integrated Alerta with ServiceNow. You say ServiceNow has a REST API so that would make integration straight-forward. There are many examples here of integrating with services that provide a web API   https://github.com/alerta/alerta-contrib/tree/master/plugins

**Comment by wo250012** [comment]
FYI, we have integrated "loosely" with ServiceNow (ITOM). We created a plugin in alerta that would forwards alerts via the snow api. We also update the alerts in snow when they get acked or closed in alerta. One thing that is a little tricky is that you have to get the snow sys_id for the alert you want to modify after it has been created. We store the alerta alert.id as the message_key when we create an alert there. In order to modify the alert we have to do a search of the alerts in snow based on this alert.id. Then we can use the returned sys_id to modify the alert in snow. Hope that makes sense.

**Comment by satterly** [comment]
Thanks for that @wo250012
