### ISSUE TITLE
Alerta customers facing 403 issues reading alerts

### ISSUE THREAD

**Issue by kavanat** [alerta/alerta#1504]
**Issue Summary**
Missing required scope: read:alerts (403).

**Environment**
- OS: [Linux]
- API version: [8.3.3]
- Deployment: [self-hosted]

- Database: [Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider?Baisc
  Customer views? Yes
  (or provide the `/config` endpoint output)

- web UI version: [8.5.0]

Error: Missing required scope:read alerts for all our alerta customer. As admin account we dont have any issues. Only customer alerts this issue is observed. In previous versions we didn't have this issue. After upgrading facing this issue

**Comment by satterly** [comment]
You haven't explained what you were doing when you got the alert.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by kavanat** [comment]
Hello @satterly ,

Just logging in to alerta web ui is giving this error as customer

**Comment by kavanat** [comment]
Any http request made to fetching alerts is giving this error. Is there any way to update default settings for customers in alerta configuration ?

**Comment by kavanat** [comment]
We have one admin account which has all access and that has no issues

**Comment by satterly** [comment]
Github issues is not the best place to resolve problems like this. Issues should be raised for bugs or feature requests, not configuration problems. Please use [Slack](https://slack.alerta.dev/) from now on. Thanks.
