### ISSUE TITLE
alertad.conf settings not taken into account (same settings working if put inside the alerta.conf file)

### ISSUE THREAD

**Issue by AndreaLVR** [alerta/alerta#1537]
Hi, 
I am facing a problem with some settings in the alertad.conf file. I state that I'm using Alerta inside a docker container, but I doubt that is the source of the problem.
What I am trying to do is simply preventing Alerta from automatically deleting the alerts after a certain period of time.
Below are the relevant environment variables and the contents of **/app/alertad.conf**, **/app/alerta.conf** and **/web/config.json**.

- environment variables:

**ALERTA_SVR_CONF_FILE=/app/alertad.conf
ALERTA_CONF_FILE=/app/alerta.conf**

- /app/alertad.conf:

**DEFAULT_EXPIRED_DELETE_HRS = 0
DEFAULT_INFO_DELETE_HRS = 0**

- /app/alerta.conf:

**[DEFAULT]
endpoint = http://localhost:8080/api**

- /web/config.json:

**{"endpoint": "http://localhost:8080/api"}**

Despite the settings in the /app/alertad.conf file, the alerts are cleared shortly after their insertion, but the interesting thing is that **if I copy the exact content of /app/alertad.conf into /app/alerta.conf then everything works as expected** and the alerts are no longer deleted.

Is there something that I am wrong or that I misunderstood? Thank you in advance.

**Comment by satterly** [comment]
You don't say what version you are running.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by CWollinger** [comment]
Hi,

I have the same problem. I don't want to delete closed alarms. 
For this I set `DEFAULT_EXPIRED_DELETE_HRS = 0` in the `alertad.conf` - with no effect.

I can only find closed alarms not older than 2 hours.
Using alerta 8.5.0.

Regards
CWollinger

**Comment by CWollinger** [comment]
Found a old issue #1493

Will try the parameter `DELETE_EXPIRED_AFTER = 0` and come back with a comment.

**Comment by AndreaLVR** [comment]
Sorry, I am using this version:

![image](https://user-images.githubusercontent.com/32772289/121671063-686c9980-caae-11eb-9d42-a5e81087c830.png)

**Comment by CWollinger** [comment]
The parameter `DELETE_EXPIRED_AFTER = 0` or `DELETE_EXPIRED_AFTER = 240` dosn't work, too

**Comment by CWollinger** [comment]
I found the solution in the docker-alerta repo/commit: https://github.com/alerta/docker-alerta/commit/9aa906c605755a4dbd17dcd5911f61683252f91f

Supervisord for the housekeeping is running in the docker container. The housekeeping reference the var `HK_EXPIRED_DELETE_HRS` & `HK_INFO_DELETE_HRS` which is set to 2 and 12 hours in the Dockerfile.

To change this you have to set/override the var in your docker environment  e.g. docker-compose file.

The other variables in alertad.conf are not suitable/used for docker.
Maybe a lack of documentation here.

@AndreaLVR hope this will help you

**Comment by AndreaLVR** [comment]
Thank you so much, @CWollinger.

**Comment by hugoShaka** [comment]
Hello @satterly 

I believe this is a regression introduced by https://github.com/alerta/alerta/pull/1508.

Passing `DEFAULT_EXPIRED_DELETE_HRS` and `DEFAULT_INFO_DELETE_HRS` in `alertad.conf` is ignored since 8.6.0. I was running with 1 week of retention and upgrading from 8.4.1 to 8.6.0 triggered an aggressive housekeeping flushing almost all of the alerts.

In the following piece of code the backward compatibility is kept only for environment variables. `get_config()` is never called on `DEFAULT_EXPIRED_DELETE_HRS`, thus `alertad.conf` is ignored for those two parameters.

https://github.com/alerta/alerta/blob/50593511d6fc29c627797eec3c32d3877ccd2b6e/alerta/utils/config.py#L79-L84
