### ISSUE TITLE
unable to ack: invalid action for current closed status(409)

### ISSUE THREAD

**Issue by arindamchoudhury** [alerta/alerta#1634]
**Issue Summary**
The alert was in blackout.
When blackout finishes we close and open alert so it can get out of blackout.
When we try to ack the open alert it fails saying: invalid action for current closed status(409).
We use postgres, i checked the status in the database, it's status is open. 

**Environment**
- OS: debian buster
- API version: 8.6.3
- Deployment: Docker
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Google
  Customer views? Yes

- web UI version: 8.6.1
- CLI version: 8.5.1

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).
