### ISSUE TITLE
(feature request) Generic JSON input?

### ISSUE THREAD

**Issue by 3IWOH** [alerta/alerta#488]
Hi-

I have a situation where we have an alert source that can send JSON to Alerta in "mostly" the correct format. The issue is that this tool makes some assumptions about the output of the replacement variables it uses to create the JSON payload and they don't map directly to the Alerta JSON format (list vs. key-value pairs for example).

My plan is to try to bring this data under other fields like text and attributes or maybe raw-data and then run a plugin to parse this and create the "real" alert for Alerta to consume. Seems possible but I have not dug in yet.

This got me thinking that it would be a great feature to allow some sort of "generic" Json Alerta endpoint for tools that don't have a lot of data formatting options. The expectation would be that this data would always go thru a custom plugin in alerta to parse/format things to the standard alert format.

thanks!

**Comment by satterly** [comment]
Interesting idea. Are you able to tell me what the alert source is so that I have a concrete use case to work with? If you can't, or it's an external tool that I wouldn't have access to anyway that is fine but it would be a useful starting point.

**Comment by 3IMOH** [comment]
Sure, the tool is DynaTrace Managed. It is a hybrid setup where the monitoring server runs locally but all the configuration and dashboards, etc are done in a cloud instance. We don't really have access to anything beyond the web UI configs.

I could also write an intermediate listener that could take the alerts and transform them before sending them on to Alerta but trying to do it all in the tool. I was able to output all of the available DynaTrace variables in the rawData field so I think I can just parse what I need from there. If that works this enhancement might not be necessary, though it might be cleaner to parse JSON to JSON instead of parsing the text of the rawData field...will let you know how it goes.

**Comment by satterly** [comment]
I have a working prototype that allows you to register custom webhooks the same way plugins work. See https://github.com/alerta/alerta/pull/489

If you could test this and give me some feedback that would be great.
