### ISSUE TITLE
Multiple similar alerts from the same instance are merged to the single alert

### ISSUE THREAD

**Issue by dkalashnik** [alerta/alerta#518]
In my setup I have two different targets on the same node:
![image](https://user-images.githubusercontent.com/4476901/38816204-a1627302-41a6-11e8-98d3-dc8ca17087b6.png)

After getting that alerts in alerta they are merging:
![image](https://user-images.githubusercontent.com/4476901/38816490-42600cf6-41a7-11e8-8856-6e2bfc5ede38.png)

So I assume `group` field is also required inside `is_duplicate ` function.

**Comment by dkalashnik** [comment]
By default `resource` is coming from `instance` which is targets' `address:port`.
I did replace it with hostname for better readability, default one is useless.

I am just thinking that having `group` which is prometheus `job` as part of PK for deduplication is also reasonable.

**Comment by satterly** [comment]
when you say you replaced instance with hostname for `resource`, did you replace it with `hostname:port` or just `hostname` ?

**Comment by dkalashnik** [comment]
Just hostname, because port gives no useful information.
I mean I get how to avoid that situation: just make instance unique for each target.

But question is still the same: does making `group` a part of primary key have sense?
From my point of view it is reasonable. There can be multiple groups (jobs in prometheus) which contains multiple targets. And some of them are on the same nodes, like in my example, fluentd and telegraf.

**Comment by satterly** [comment]
In your case, "port" is useful because in combination with hostname it makes the target unique -- which is what will prevent the different instances merging into the same alert. Currently, a unique alert is defined by a unique combination of `customer-environment-resource-event`.

Using `group` to namespace `resource` (in addition to the above) might make sense for this particular use case however it could overcomplicate deduplication for the vast majority of cases. Also, would it make more sense to namespace `resource` using `environment` -- which is what it was designed for?

Another aspect is that `group` was actually intended to [group "events" not "resources"](http://docs.alerta.io/en/latest/conventions.html#event-groups). So although this isn't a hard and fast rule, it does have to potential to be another confusing factor.

**Comment by dkalashnik** [comment]
Ok, got it, thanks.
