### ISSUE TITLE
Unable to disable auto refresh

### ISSUE THREAD

**Issue by jeremystretch** [alerta/alerta#557]
The [documentation](https://alerta.readthedocs.io/en/latest/configuration.html) indicates that defining `AUTO_REFRESH_ALLOW='OFF'` will disable automatic refreshing of the alerts list in the web UI. However, I can't get this to work. It looks like the setting may have been removed in 5.x. Am I missing something?

**Comment by Anderen2** [comment]
I believe the documentation may be misleading there, I cannot see that it is any config variable used with the name "AUTO_REFRESH_ALLOW". 

However, there are a runtime switch that may be used to change the auto-refresh on and off named "auto-refresh-allow". 
This may be toggled by eg. using curl as follows:
`curl -XPOST -F "auto-refresh-allow=OFF" -H "Authorization: Key <APIKey-with-admin>" <alerta-server>/api/management/switchboard`
Replace <APIKey-with-admin> with a API key that has admin access and <alerta-server> with the Alerta server address

**Comment by jeremystretch** [comment]
That seems to do it, thanks. Oddly, the UI will still auto-refresh 2-5 times before changing to a manual "refresh" button.

**Comment by satterly** [comment]
There can be inconsistencies in the switch status if you have multiple Alerta API servers because the switch status is held in-memory (per server) when really it should be stored in the database (shared). This is on the backlog to fix.

And by the way, there is a rudimentary UI to allow you to toggle API switches. See for example https://alerta-api.herokuapp.com/management/switchboard?api-key=Qvu7HTuu6x5MCWVx_L9zD17RSfELLpDXh40_DC22

<img width="539" alt="screen shot 2018-06-12 at 23 40 34" src="https://user-images.githubusercontent.com/615057/41318858-0bf569ac-6e9a-11e8-9af8-c728de39cc66.png">
