### ISSUE TITLE
Alert history not showing newest status changes

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#592]
it seems to be that we can see at history only 100 (by default) events since the first, is there any possibility to revert this list? we can't see fresh acknowledges if there are too many alerts
I talk about /alert/:id page

Database: Postgres

/cc @asvad3389

**Comment by mmulqueen** [comment]
Just wanted to say I've noticed the same thing with alerts that don't have a chance to expire - heartbeats in particular, but also other frequent events. Started to look into it yesterday. The 100 limit seems to come from alerta/models/alert.py, the code calls db.get_history with a page size of 100. We're also using PostgreSQL as the database, but it looks like the same would apply to Mongo as well. I don't think this is a new issue, but I've noticed this before and not had a chance to look at it. One option would be to get the event history in descending order instead (i.e. the 100 most recent events), from what I can see, this looks like it shouldn't cause problems because get_history only seems to feed the web API not anything internal.

I'm a bit concerned that this event history will keep growing forever. Maybe we ought to add something to housekeeping to clean up old event history even if the alert itself doesn't expire?

**Comment by satterly** [comment]
The alert history array is being limited to the `HISTORY_LIMIT` (which defaults to "100"). Whenever a new history update is added to the array the array is "sliced" to limit the number of elements so it doesn't grow forever. However, the slice range was wrong so it was always dropping off the newest element of the array instead of the oldest. This should be fixed by #601.
