### ISSUE TITLE
CreatedTime in deduplication history

### ISSUE THREAD

**Issue by bennneuh** [alerta/alerta#597]
Hello,

Is it possible to add the CreatedTime info in the deduplication history to be able to follow when the deduplication occure ?

Because finally, without the visibility in CreatedTime with each deduplication, we loose when the real alert has been created and we just see the "Update Time".

So if for some reasons the flow of alerts has been stopped temporary and is re-enabled, in case of deduplication, we are flooded with lot's of "Update Time" without knowing when the real alert has been generated.

I hope i'm clear...

Thanks,

Benoît

**Comment by satterly** [comment]
I'm pretty sure I understand the issue. Instead of adding create time, I've decided to consistently use the create time for update time when the alert history entry is alert-driven. ie. if a user acks an event that will still use "now" as the update time, however, if an alert is deduplicated it will use the create time of the alert as the update time.
