### ISSUE TITLE
Unable to create API key using "alerta"

### ISSUE THREAD

**Issue by heydonovan** [alerta/alerta#621]
```
07:34:54 AM $ alerta key --username 'admin@email.com' --scope admin:keys --text application --customer test123
ERROR: Expecting value: line 1 column 1 (char 0)
```

I'm not sure what else to do here, I'll keep digging around. :v:

**Comment by satterly** [comment]
Run again with `--debug` option this time. Thanks.

**Comment by satterly** [comment]
I get this error if the `alerta` client tries to connect to an http endpoint that returns HTML instead of JSON. This makes me think you haven't configured the `endpoint` correctly. I've included an example below ...

```
$ cat ~/.alerta.conf
[DEFAULT]
sslverify = yes
output = psql
timezone = Europe/London

[profile heroku]
endpoint = https://alerta-api.herokuapp.com
key = demo-key
timeout = 30

[profile docker]
endpoint = http://localhost:9080/api
key = 0Y-0DrGWaaRdhCCAV3Sw27_CMDmC7JPgU7m9y4pA
```

If you're still having problems please run `alerta` with the `--debug` option like this and add the output below.

```
$ alerta --debug key --username 'admin@email.com' --scope admin:keys --text application --customer test123
```
