### ISSUE TITLE
Cannot disable signup feature by using SIGNUP_ENABLED env variable

### ISSUE THREAD

**Issue by psyhomb** [alerta/alerta#768]
**Describe the bug**
I really don't know if this is a bug or I'm missing something but I cannot disable signup feature by using `SIGNUP_ENABLED` environment variable.

**To Reproduce**
Added environment variable `SIGNUP_ENABLED=False` after which I can still see through the config api that signup feature is enabled and I can signup/create a new account via WebUI.

```
$ docker inspect web | jq -r '.[].Config.Env[2]'
SIGNUP_ENABLED=False
$
```

```
$ curl -sSL 'http://localhost:8080/api/config' | jq '.signup_enabled'
true
$
```

**Expected behavior**
```
$ docker inspect web | jq -r '.[].Config.Env[2]'
SIGNUP_ENABLED=False
$
```

```
$ curl -sSL 'http://localhost:8080/api/config' | jq '.signup_enabled'
false
$
```

**OS**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$
``` 
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
$
```

**Comment by satterly** [comment]
`SIGNUP_ENABLED` can not be set using an environment variable. Use a config file instead.

**Comment by psyhomb** [comment]
I already configured that through docker-compose 
```

**Comment by satterly** [comment]
Alerta currently supports setting 30 out of more than 60 configuration options as environment variables because they are commonly used in standard deployments. Some of the config options like [`LDAP_DOMAINS`](https://docs.alerta.io/en/latest/authentication.html?highlight=ldap#basic-auth-using-ldap) (a dictionary) would be difficult to support as environment variables.

I'm not sure how expecting a single configuration file for complex deployments is more onerous than having to keep track of dozens of environment variables. If you're using a configuration management tool (as you should be) the method of getting the application config on to the server should be transparent / irrelevant. 

Anyway I'll take on board your comments and may reconsider this in future. Thanks for the feedback.

**Comment by psyhomb** [comment]
> I'm not sure how expecting a single configuration file for complex deployments is more onerous than having to keep track of dozens of environment variables.

You are absolutely right about that but I'm not talking about all environment variables just a small portion of them have to be changed from time to time from their default values, for example `SINGUP_ENABLED` parameter the very reason I've opened this issue :wink:.

>If you're using a configuration management tool (as you should be) the method of getting the application config on to the server should be transparent / irrelevant.

There are situations when you don't have access to the host filesystem (managed services).

Anyway I think that `SINGUP_ENABLED` parameter is good candidate for env variables.

@satterly thanks for all the help and keep up a good work.

Cheers

**Comment by satterly** [comment]
You've convinced me 😄 My issue is knowing where to draw the line between standard and complex configuration settings. I think this is setting is more common than not.
